### ISSUE TITLE
Add basic create Todo item UI

### ISSUE THREAD

**Issue by lucas-neuhauss** [Neuhaus93/Todoist-Clone#3]
Add the functionality to:

- [x] Clicking the Plus button should open a small modal on the bottom, focused on the title input field;
- [x] Clicking on the backdrop should close it;
- [x] Task name is required, due date is not required. Create button should be disabled until the required fields are set.

* Disabled button bg: `#e5e5e5`

<img alt="Inbox Layout" src="https://user-images.githubusercontent.com/38574361/227820256-de6ddbc0-60d7-4c49-a0ff-504fbee4aaa0.png" width="350" />
